# Generated by Django 3.0.3 on 2020-07-21 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.TextField()),
                ('Description', models.TextField()),
                ('Views', models.IntegerField()),
                ('Rating', models.DecimalField(decimal_places=6, max_digits=10)),
                ('Duration', models.IntegerField()),
                ('Captions', models.TextField()),
                ('PodNum', models.IntegerField()),
                ('TextSegments', models.TextField()),
                ('CaptionWords', models.TextField()),
                ('Name', models.TextField()),
                ('TextIntervalDicts', models.TextField()),
            ],
            options={
                'db_table': '../jreDB',
                'managed': False,
            },
        ),
    ]
