# Generated by Django 3.0.3 on 2020-07-21 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('captionAnalysis', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='mymodel',
            table='../jreDB.db',
        ),
    ]
