# Generated by Django 3.0.3 on 2020-07-21 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('captionAnalysis', '0002_auto_20200722_0008'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='mymodel',
            table='JRE',
        ),
    ]
