# Generated by Django 3.0.3 on 2020-07-21 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('captionAnalysis', '0003_auto_20200722_0030'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mymodel',
            options={'managed': True},
        ),
    ]
