# Generated by Django 3.0.3 on 2020-07-21 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('captionAnalysis', '0004_auto_20200722_0153'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mymodel',
            options={'managed': False},
        ),
    ]
